- .gitignore
- docs/request_field_names_and_descriptions.json
- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/ai_horde_api/apimodels/generate/_status.py
- horde_sdk/ai_horde_api/apimodels/generate/_submit.py
- horde_sdk/ai_horde_api/consts.py
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_submit_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_submit_post.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_status_id_delete_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_status_id_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_text_pop_post_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_text_status_id_delete_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_text_status_id_get_200.json
See https://github.com/Haidra-Org/AI-Horde/issues/315 for more information.
> feat: Add support for gen_metadata key (#69)

- horde_sdk/ai_horde_api/apimodels/__init__.py
- horde_sdk/ai_horde_api/apimodels/base.py
fix: allow import GenMetadataEntry from base 
fix: make ref optional in GenMetadataEntry
> fix: `GenMetadataEntry` adjustments

- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/generic_api/apimodels.py
> fix: don't crash when extra/new fields are returned due to api changes

- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/generic_api/apimodels.py
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_interrogate_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_users_user_id_put.json
- tests/test_data/ai_horde_api/example_responses/_v2_find_user_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_text_pop_post_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_user_id_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_user_id_put_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_workers_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_workers_worker_id_get_200.json
- Updates test files to include the data model changes to the API made in https://github.com/Haidra-Org/AI-Horde/pull/332
> fix: include latest data model schemas

- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/ai_horde_api/apimodels/generate/_submit.py
- horde_sdk/generic_api/apimodels.py
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_interrogate_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_users_user_id_put.json
- tests/test_data/ai_horde_api/example_responses/_v2_find_user_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_text_pop_post_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_user_id_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_user_id_put_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_workers_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_workers_worker_id_get_200.json
- Synchronizes more fields recently added to the API
- Minor fix where a message was displayed incorrectly at the error level
> feat: support for lora is_version

- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/ai_horde_api/consts.py
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_async_post.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_pop_post_200.json
See https://github.com/Haidra-Org/AI-Horde/commit/5b6014877782f2ce73e49f4cceae1eb67f272fc3 for the relevant horde change.
> feat: support lcm sampler

- horde_sdk/ai_horde_api/apimodels/alchemy/_status.py
- horde_sdk/ai_horde_api/apimodels/base.py
- tests/ai_horde_api/test_ai_horde_api_models.py
> fix: allow arbitrary sampler/upscaler names

- horde_sdk/ai_horde_api/apimodels/alchemy/_async.py
- horde_sdk/ai_horde_api/apimodels/alchemy/_pop.py
- horde_sdk/ai_horde_api/apimodels/alchemy/_status.py
- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/ai_horde_api/consts.py
- tests/ai_horde_api/test_ai_horde_api_models.py
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_pop_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_interrogate_pop_post.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_pop_post_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_workers_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_workers_worker_id_get_200.json
* allow_batching is async payloads
* batch_index in gen_metadata
> feat: extend sdk to handle batch stuff

- horde_sdk/ai_horde_api/apimodels/base.py
- tests/ai_horde_api/test_ai_horde_api_models.py
> fix: logic issue with `KNOWN_SAMPLERS` check

- horde_sdk/ai_horde_api/apimodels/generate/_pop.py
- tests/ai_horde_api/test_ai_horde_api_models.py
The test conditions of a fresh horde didn't reveal the problem in the logic with `skipped`. This should resolve the issue, and tests for it for the future.
> fix: skipped logic mishap

- horde_sdk/ai_horde_api/ai_horde_clients.py
- horde_sdk/ai_horde_api/apimodels/alchemy/_async.py
- horde_sdk/ai_horde_api/apimodels/alchemy/_status.py
- horde_sdk/ai_horde_worker/bridge_data.py
- horde_sdk/ai_horde_worker/model_meta.py
- horde_sdk/generic_api/apimodels.py
- requirements.txt
- tests/ai_horde_worker/test_model_meta.py
- See #155 for more information.
> feat: more model meta load instructions

- horde_sdk/ai_horde_api/apimodels/generate/_pop.py
- tests/ai_horde_api/test_ai_horde_api_models.py
> fix: check by value for KNOWN_UPSCALERS enum membership

- horde_sdk/ai_horde_api/consts.py
Supports new source processing which will trigger the remix pipeline
> feat: support remix

- codegen/ai_horde_codegen_10072023.py
- docs/request_field_names_and_descriptions.json
- docs/response_field_names_and_descriptions.json
- horde_sdk/ai_horde_api/apimodels/__init__.py
- horde_sdk/ai_horde_api/apimodels/_find_user.py
- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/ai_horde_api/apimodels/generate/_async.py
- horde_sdk/ai_horde_api/apimodels/generate/_pop.py
- horde_sdk/ai_horde_api/consts.py
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_async_post.json
- tests/test_data/ai_horde_api/example_payloads/_v2_users_user_id_put.json
- tests/test_data/ai_horde_api/example_responses/_v2_find_user_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_async_post_202.json
- tests/test_data/ai_horde_api/example_responses/_v2_generate_text_async_post_202.json
- tests/test_data/ai_horde_api/example_responses/_v2_sharedkeys_put_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_sharedkeys_sharedkey_id_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_sharedkeys_sharedkey_id_patch_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_user_id_get_200.json
- tests/test_data/ai_horde_api/example_responses/_v2_users_user_id_put_200.json
> feat: Support for extra_source_images

- .gitignore
- horde_sdk/ai_horde_api/apimodels/base.py
- horde_sdk/ai_horde_api/apimodels/generate/_async.py
- horde_sdk/ai_horde_api/apimodels/generate/_pop.py
- horde_sdk/generic_api/apimodels.py
- horde_sdk/generic_api/generic_clients.py
- tests/ai_horde_api/test_ai_horde_api_models.py
- tests/ai_horde_api/test_ai_horde_generate_api_calls.py
> fix: post remix bug fixes; don't crash on client usage

- .github/workflows/maintests.yml
- .github/workflows/prtests.yml
This should help catch changes to linting/mypy rules.
> ci: use `--all-files` with pre-commit workflow step

- requirements.txt
- See also https://github.com/Haidra-Org/horde-model-reference/pull/112
> fix: use ~0.7.0 of `horde_model_reference`

- horde_sdk/ai_horde_api/apimodels/base.py
> feat: support transparent in the payload

- horde_sdk/ai_horde_api/apimodels/base.py
- See #216 for more information.
> feat: `hires_fix_denoising_strength`

- .pre-commit-config.yaml
- requirements.txt
This should helpfully resolve some dependency whack-a-mole.
> fix: use latest known `horde_model_reference`

- examples/ai_horde_client/workers.py
- horde_sdk/ai_horde_api/ai_horde_clients.py
- horde_sdk/ai_horde_api/apimodels/workers/_workers.py
> feat: support for seek by worker name

- examples/ai_horde_client/image/async_manual_client_example.py
- examples/ai_horde_client/image/async_simple_client_example.py
- examples/ai_horde_client/text/async_text_generate.py
- horde_sdk/__init__.py
- tests/conftest.py
See https://github.com/aio-libs/aiodns/issues/86 for more information.
> fix: `set_event_loop_policy` for win32

- examples/ai_horde_client/image/async_manual_client_example.py
- examples/ai_horde_client/image/async_simple_client_example.py
- examples/ai_horde_client/text/async_text_generate.py
- horde_sdk/__init__.py
- tests/conftest.py
- See f6ff2266611f70fa758f3959bb037b708237abec for more info.
> fix: set_event_loop_policy for win32 

- horde_sdk/ai_horde_api/apimodels/generate/_pop.py
- tests/ai_horde_api/test_ai_horde_api_models.py
- See https://github.com/Haidra-Org/horde-worker-reGen/issues/242 for one of the initial reports of this.
- Related to https://github.com/Haidra-Org/AI-Horde/pull/453 and the (now reverted) investigative/test commits which exposed this problem.
> fix: sort r2_uploads so it matches `ids` sort

- .pre-commit-config.yaml
- codegen/ai_horde/swagger.json
- codegen/ai_horde/swagger_openapi3.json
- horde_sdk/ai_horde_api/consts.py
- requirements.dev.txt
- See #265 for more information.
- Includes #262 as well with an update to ruff.
> feat: `information` metadata key

- examples/ai_horde_client/image/async_manual_client_example.py
- horde_sdk/__init__.py
- horde_sdk/ai_horde_api/ai_horde_clients.py
- horde_sdk/generic_api/apimodels.py
- horde_sdk/generic_api/generic_clients.py
- See #271 for more information.
> fix: use new default ssl context in all aiohttp requests (#271)

- .pre-commit-config.yaml
- horde_sdk/generic_api/apimodels.py
- requirements.dev.txt
- See #297 for more information.
> fix: allow extra attribs for HordeAPIObject 

- horde_sdk/generic_api/apimodels.py
This reverts commit 174107ac61cdd00dcb8414d919d233a15ee143c2.
> Revert "fix: allow extra attribs for HordeAPIObject"

- horde_sdk/ai_horde_api/ai_horde_clients.py
- horde_sdk/generic_api/generic_clients.py
- horde_sdk/horde_logging.py
- See #317 for more information
> fix: expose apikey as intended
