Haidra-Org/horde-sdk

.gitignore, examples/ai_horde_api_client.example.py, examples/async_ai_horde_api_client_example.py, horde_sdk/ai_horde_api/__init__.py, horde_sdk/ai_horde_api/ai_horde_client.py, horde_sdk/ai_horde_api/apimodels/generate/_async.py, horde_sdk/ai_horde_api/apimodels/generate/_status.py, horde_sdk/generic_api/apimodels.py, horde_sdk/generic_api/generic_client.py, horde_sdk/generic_api/metadata.py, horde_sdk/ratings_api/apimodels.py, horde_sdk/ratings_api/ratings_client.py, pyproject.toml, requirements.dev.txt, requirements.txt, tests/ai_horde_api/test_ai_horde_api_calls.py, tests/conftest.py
- e.g. `AIHordeAPISimpleClient`, `AIHordeAPISession`, and `AIHordeAPIClient` all support `async`/`await` operations.
- Requests which require some sort of follow up, such as image generation requests, now can have the appropriate cancel request sent automatically with
- See `AIHordeAPISession` (new context handler) or its usage in `test_ai_horde_api_calls.py` for an idea of what was accomplished.
=> feat: proper asyncio support, horde context manager

horde_sdk/ai_horde_api/apimodels/generate/_async.py, horde_sdk/ai_horde_api/apimodels/generate/_pop.py, horde_sdk/ai_horde_worker/model_meta.py, pyproject.toml
- `GenerationInputStable` (`/v2/generate/async/`) on the API uses `n` and `steps`
- `GenerationPayloadStable`, which contains `ModelPayloadStable` (`/v2/generate/pop`) uses `n_iter` and `ddim_steps`
At some point along the way, I lost grasp of this, and 'fixed' it so they were consistent in the SDK. This changes things so the field name in the SDK matches the API definition, but it also accepts the corresponding name as a validation alias.
=> fix: use API visible field name for steps/n_iter

horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_api/fields.py, horde_sdk/generic_api/generic_clients.py, pyproject.toml, tests/ai_horde_api/test_dynamically_validate_against_swagger.py
On instantiating a `AIHordeAPIAsyncSimpleClient`, you now have the option of passing a `AIHordeAPIAsyncClientSession`. It is the responsibility of the caller to have used it with a `with` statement to still enable the automatically request cleanup on an exception.
This allows more flexibility in the design of loops which make these sort of calls, such as for the worker, while still having the benefits of it's context management.
=> feat: allow flexible `AIHordeAPIAsyncClientSession` context

.github/workflows/release.yml, pyproject.toml
Attempt number 1 to get pypi publishing handled by a github action as inspired by jug's take on it [in hordelib](https://github.com/Haidra-Org/hordelib/blob/main/.github/workflows/release.yml).
A notable difference is I am attempting to use [trusted publishing](https://github.com/pypa/gh-action-pypi-publish/tree/release/v1/#trusted-publishing) instead of issuing a pypi auth token.
=> ci: feat: support publish to pypi on push to `releases` branch

horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/generic_api/apimodels.py
Fixes the SDK crashing when certain API changes occur.
`extra="forbid"` wasn't really intended to be part of the production release. I will look at reworking it back into the testing somehow, as its more of sanity check for internal consistency rather than a useful feature to have.
=> fix: don't crash when extra/new fields are returned due to api changes

horde_sdk/ai_horde_api/apimodels/generate/_pop.py
`bridge_version` is deprecated. See https://github.com/Haidra-Org/AI-Horde/pull/338 for the API change for semver support (passed as the second element in the `bridge_agent` field).
=> fix: make `bridge_version` optional for dreamer job pop

horde_sdk/ai_horde_worker/bridge_data.py
This is for config file backward compatibility with `AI-Horde-Worker`
=> fix: allow `all models` meta model load command

horde_sdk/ai_horde_api/apimodels/alchemy/_status.py, horde_sdk/ai_horde_api/apimodels/base.py, tests/ai_horde_api/test_ai_horde_api_models.py
The reality is that the SDK does not need to enforce this as a strict constraint, as its possible this field (or more specifically, valid values for it) could change at any time. This relaxes the constraint to a warning printed to the console.
=> feat: support arbitrary samplers returned from the API

.github/workflows/maintests.yml, .github/workflows/prtests.yml, docs/build_docs.py, docs/response_field_names_and_descriptions.json, horde_sdk/ai_horde_api/apimodels/_find_user.py, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/generic_api/apimodels.py, pyproject.toml, tests/conftest.py, tox.ini
- This changes the default behavior of tests to forbid undefined fields in the objects returned from the API. This change aims to ensure that when SDK versions are published, they account for all of the currently defined objects and fields on the API.
- Incidentally, this PR also brings the SDK model definitions which do exist into compliance with the schema currently on the API, specifically the FindUserResponse model.
=> ci: fix: use forbid fields during ci

.github/workflows/maintests.yml, .github/workflows/prtests.yml, .pre-commit-config.yaml, docs/build_docs.py, docs/response_field_names_and_descriptions.json, horde_sdk/ai_horde_api/apimodels/_find_user.py, horde_sdk/ai_horde_api/apimodels/alchemy/_async.py, horde_sdk/ai_horde_api/apimodels/alchemy/_pop.py, horde_sdk/ai_horde_api/apimodels/alchemy/_status.py, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/consts.py, horde_sdk/generic_api/apimodels.py, horde_sdk/ratings_api/apimodels.py, horde_sdk/ratings_api/metadata.py, pyproject.toml, requirements.dev.txt, tests/ai_horde_api/test_ai_horde_api_models.py, tests/ai_horde_api/test_ai_horde_generate_api_calls.py, tests/conftest.py, tests/test_data/ai_horde_api/example_payloads/_v2_generate_async_post.json, tests/test_data/ai_horde_api/example_payloads/_v2_generate_pop_post.json, tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_async_post.json, tests/test_data/ai_horde_api/example_payloads/_v2_generate_text_pop_post.json, tests/test_data/ai_horde_api/example_payloads/_v2_interrogate_pop_post.json, tests/test_data/ai_horde_api/example_responses/_v2_generate_pop_post_200.json, tests/test_data/ai_horde_api/example_responses/_v2_workers_get_200.json, tests/test_data/ai_horde_api/example_responses/_v2_workers_worker_id_get_200.json, tox.ini
- [feat: extend sdk to handle batch stuff](https://github.com/Haidra-Org/horde-sdk/commit/d5512ecfb6480624cda9d771d39d3d3f2b7abc6c)
- Support the `allow_batching` in `/v2/aysnc/generate` payloads
- `batch_index` in `GenMetadataEntry`
- [Allow arbitrary changes to `GenMetadataEntry` values for the fields already established.](https://github.com/Haidra-Org/horde-sdk/commit/ae1e82d105df91b5bb968e8f389d2d85399bf349)
- It will now give a warning instead of a validation failure.
- Similarly, [fix: don't crash on alchemy type (form) changes](https://github.com/Haidra-Org/horde-sdk/commit/3542f821a9a046399f42609435bdc63da50b8b65)
- https://github.com/Haidra-Org/horde-sdk/pull/99
- The CI/Tests now mandate that you have support for all defined fields on the API (you can't omit fields the API …
=> feat: support more API fields; be more tolerant of API model value changes

horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_api/apimodels/__init__.py, horde_sdk/ai_horde_api/apimodels/generate/_check.py, horde_sdk/ai_horde_api/apimodels/generate/_progress.py, horde_sdk/ai_horde_api/apimodels/generate/_status.py, tests/ai_horde_api/test_ai_horde_generate_api_calls.py
- "Simple" clients (e.g., `AIHordeAPISimpleClient`, `AIHordeAPIAsyncSimpleClient`) can now pass a function that is called when a check request (or status request in the case of alchemy) is made.
- Right now, the callback will pass the check response as the first argument
- Currently, it will always be either an `ImageGenerateCheckResponse` or an `AlchemyStatusResponse` (but this will change as other endpoints are implemented/
You can see the behavior in the new tests added:
```python
@pytest.mark.asyncio
async def test_check_image_gen_callback(
self,
simple_image_gen_request: ImageGenerateAsyncRequest,
) -> None:
async with aiohttp.ClientSession() as aiohttp_session:
simple_client = AIHordeAPIAsyncSimpleClient(aiohttp_session)
def example_callback(generation: ImageGenerateCheckResponse) …
```
=> feat: allow callback for 'simple' generation requests

.pre-commit-config.yaml, horde_sdk/ai_horde_api/__init__.py, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/apimodels/generate/_pop.py, requirements.dev.txt, tests/ai_horde_api/test_ai_horde_api_models.py
- `has_upscaler` and `has_facefixer` properties for `ImageGenerateJobPopResponse`
- This should be in the continued sprit of separating concerns from the worker code when API changes happen.
- Will now print a warning when a currently unknown `control_type` or `post_processor` is passed.
=> feat: more props. for `ImageGenerateJobPopResponse`; show more warnings on unknown field values

horde_sdk/ai_horde_api/apimodels/alchemy/_async.py, horde_sdk/ai_horde_api/apimodels/alchemy/_status.py, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/consts.py, tests/ai_horde_api/test_ai_horde_api_models.py
- Check for expected types more rigorously with enum values
- Fixes the corner case where the enum member name doesn't match the API name (as with `4x_AnimeSharp`)
=> fix: handle enum validation better

horde_sdk/ai_horde_api/apimodels/base.py, tests/ai_horde_api/test_ai_horde_api_models.py
A double negative caused some confusion in writing the enum values check. See diff.
=> fix: logic issue with KNOWN_SAMPLERS check

horde_sdk/ai_horde_api/apimodels/base.py, tests/ai_horde_api/test_ai_horde_api_models.py
In the same vein as https://github.com/Haidra-Org/horde-sdk/pull/129, this fixes the logic for the enum membership check for the `ImageGenerateParamMixin` class, used to confirm payloads/responses for image generate requests are using expected values.
=> fix: correct logic for `KNOWN_CONTROLNET` check

horde_sdk/ai_horde_api/apimodels/generate/_pop.py, tests/ai_horde_api/test_ai_horde_api_models.py
=> fix: skipped logic

requirements.txt
The compatibility version pin is unnecessary for the SDK.
=> feat: allow latest `horde_model_reference` versions

horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_api/apimodels/alchemy/_async.py, horde_sdk/ai_horde_api/apimodels/alchemy/_status.py, horde_sdk/ai_horde_worker/bridge_data.py, horde_sdk/ai_horde_worker/model_meta.py, horde_sdk/generic_api/apimodels.py, requirements.txt, tests/ai_horde_worker/test_model_meta.py
- Meta load commands are now supported in for `models_to_skip`
- `ALL SDXL`, `ALL SD15`, `ALL SD21`, `ALL SFW`, `ALL NSFW` are now all valid model meta load (or skip) instructions.
- An oversight led to warnings being generated during alchemy generate requests. This has been corrected.
=> feat: more model meta instructions + allow meta in skip models; fix: allow unknown alchemy types

horde_sdk/ai_horde_api/apimodels/generate/_pop.py, tests/ai_horde_api/test_ai_horde_api_models.py
This was causing 4x_AnimeSharp to not be recognized correctly and dropped by the worker.
=> fix: check by value for KNOWN_UPSCALERS enum membership

.gitignore, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/apimodels/generate/_async.py, horde_sdk/ai_horde_api/apimodels/generate/_pop.py, horde_sdk/generic_api/apimodels.py, horde_sdk/generic_api/generic_clients.py, tests/ai_horde_api/test_ai_horde_api_models.py, tests/ai_horde_api/test_ai_horde_generate_api_calls.py
- [An oversight](484e04a4afdd91fe0424d95cc95ea5218dbf6e34) led to most client requests crashing the SDK. This has been fixed.
- `ImageGenerateJobPopResponse` (and in the future, any child class of `ResponseRequiringDownloadMixin`) can now support (asynchronously) downloading the `source_image`, `source_mask` and `extra_source_images` fields in the SDK.
- This is part of the continued effort of de-coupling the worker from the SDK wherever possible.
- A few minor fixes, such as not logging base64 image information to the log, and using `AI_HORDE_DEV_APIKEY` as the default API key when it is set.
=> fix: post remix bug fixes; don't crash on client usage

horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/apimodels/generate/_pop.py, tests/ai_horde_api/test_ai_horde_api_models.py
This helps decouple a potential headache from having to be handled by the worker in the case of extra images failing to download.
=> feat: handle extra image retries

horde_sdk/ai_horde_api/apimodels/workers/_workers_all.py, pyproject.toml
- Removes a long-forgotten about attr in `AllWorkersDetailsResponse` which now causes a breaking runtime exception with `pydantic` 2.7.0.
- Silences warnings about soon to be deprecated `ruff` configuration sections in `pyproject.toml`.
=> fix: support pydantic 2.7.0; chore: conform with new ruff pyproject.toml section format

.pre-commit-config.yaml, horde_sdk/ai_horde_api/apimodels/workers/_workers_all.py, pyproject.toml, requirements.dev.txt
See #175 for more information.
=> fix: support pydantic 2.7.0

.github/workflows/maintests.yml, .github/workflows/prtests.yml
This brings this repo in line with the standard expectation of support for at least python 3.11.
=> ci: test python 3.11 too

.gitignore, docs/horde_sdk/_version.md
This is not a documentable object and would not appear in the repo/docs under ordinary circumstances.
=> docs: removes `_version.md`

.github/workflows/maintests.yml, .github/workflows/prtests.yml, .pre-commit-config.yaml, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/apimodels/generate/_pop.py, horde_sdk/generic_api/apimodels.py, pyproject.toml, requirements.txt, tests/ai_horde_api/test_ai_worker_roundtrip_api_calls.py, tests/conftest.py, tox.ini
- An initial test designed for testing worker functionality of the API of AI-Horde during it's CI runs
- `validate_ids_present` now works as intended. ([fix: implement ids_present as intended](https://github.com/Haidra-Org/horde-sdk/commit/8097e567e555cd7d46f510a2ca64cc41bf80cfe1))
- Certain fields were defaulting to empty lists (or otherwise not `None`) despite the API not returning them. They now are unset (`None`) as intended (https://github.com/Haidra-Org/horde-sdk/commit/ea5e04c91c543d8c96fdb1ef03c084f48a289fea)
=> tests: api side worker test; fix: misc fixes

examples/ai_horde_client/workers.py, horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_api/apimodels/workers/_workers.py
- See #243 for more information
=> feat: support for seek by worker name (#243)

CONTRIBUTING.md, docs/api_to_sdk_map.md, docs/api_to_sdk_payload_map.json, docs/api_to_sdk_response_map.json, docs/request_field_names_and_descriptions.json, examples/ai_horde_client/workers.py, horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_api/apimodels/__init__.py, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/apimodels/workers/_workers.py, horde_sdk/ai_horde_api/endpoints.py, horde_sdk/ai_horde_api/metadata.py, horde_sdk/scripts/write_all_response_examples_for_tests.py, tests/test_data/ai_horde_api/example_responses/_v2_workers_name_worker_name_get_200.json
=> feat: Adds worker_details_by_name

CONTRIBUTING.md, docs/api_to_sdk_map.md, docs/api_to_sdk_payload_map.json, docs/api_to_sdk_response_map.json, docs/request_field_names_and_descriptions.json, examples/ai_horde_client/workers.py, horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_api/apimodels/__init__.py, horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/ai_horde_api/apimodels/workers/_workers.py, horde_sdk/ai_horde_api/endpoints.py, horde_sdk/ai_horde_api/metadata.py, horde_sdk/scripts/write_all_response_examples_for_tests.py, tests/test_data/ai_horde_api/example_responses/_v2_workers_name_worker_name_get_200.json
- See #247 for more information.
=> feat: workers by name

.pre-commit-config.yaml, horde_sdk/generic_api/apimodels.py, horde_sdk/horde_logging.py, requirements.dev.txt, requirements.txt
- The most recent version of pydantic resolves some typing related issues to do with BaseModels, particularly for the `default` arg for `Field`.
- Fixes a typo in the default client agent string (thanks @Luke100000) 
- Updates all linting/formatting/ci dependencies with a corresponding non-functional change to the code in `horde_logging.py` to comply with the latest version of a ruff rule.
=> feat: use `pydantic==2.9.2`; chore: update dev deps

horde_sdk/__init__.py, horde_sdk/ai_horde_worker/model_meta.py, tests/ai_horde_worker/test_model_meta_api_calls.py
Controlled by `AI_HORDE_MODEL_META_LARGE_MODELS`. Any non-null value will allow very large models, such as cascade and flux, to be returned from model meta commands.
=> feat: remove large models from model meta commands

codegen/ai_horde/swagger.json, codegen/ai_horde/swagger_openapi3.json, horde_sdk/ai_horde_api/consts.py
New `information` key will hold whether the image is nsfw or not, but in the future is open ended enough to be expanded with `see_ref` with more arbitrary info if needed.
Necessary for https://github.com/Haidra-Org/AI-Horde/issues/442
=> feat: Adds the exta information metadata key

.github/workflows/maintests.yml, .github/workflows/prtests.yml, horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/generic_api/generic_clients.py, requirements.txt
The hope of this change is to fix an issue where uploads to cloudflare on a fresh windows 10 pro machine would fail due to being unable to resolve the system's cert store for the relevant root authority certificate. Despite being sure the cert was installed and various other troubleshooting efforts, only by utilizing certifi to resolve the cert store ultimately resolved the issue.
=> fix: use a default `certifi` based ssl context

.github/workflows/maintests.yml, .github/workflows/prtests.yml, horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/generic_api/generic_clients.py, requirements.txt
=> fix; use a default certifi based ssl context

examples/ai_horde_client/image/async_manual_client_example.py, horde_sdk/__init__.py, horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/generic_api/apimodels.py, horde_sdk/generic_api/generic_clients.py
Adds the missing ssl kwarg usage in other parts of the code, missed in https://github.com/Haidra-Org/horde-sdk/pull/268.
=> fix: use new default ssl context in all aiohttp requests

horde_sdk/ai_horde_api/apimodels/base.py, horde_sdk/generic_api/apimodels.py
This doesn't automatically bring support for any intended functionality but in the case of informational model dumps, such as for the `skipped` info on a job pop or user/worker info responses this will allow some forward compatibility in the case new fields are added to already known API models.
=> fix: config default root models to allow new API fields

horde_sdk/generic_api/apimodels.py
This makes this class consistent with `HordeAPIDataObject` and my intentions. Practically speaking, for forward compatibility and in a live situation we want to allow additional information to propagate from the API to an end user where possible.
=> fix: allow extra attribs for HordeAPIObject

horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_worker/model_meta.py, horde_sdk/horde_logging.py
This fixes the behavior of workers attempting to load recently removed (and therefore previously known) models when using the `TOP` meta model load command
=> fix: support model_state for model load meta

horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/ai_horde_worker/model_meta.py
* fix: support model_state for model load meta
This fixes the behavior of workers attempting to load recently removed (and therefore previously known) models when using the `TOP` meta model load command
=> fix: support model_state for model load meta (#313)

horde_sdk/ai_horde_api/ai_horde_clients.py, horde_sdk/generic_api/generic_clients.py, horde_sdk/horde_logging.py
The failure to expose this argument leads to recovery operations not working as intended/expected
=> fix: expose apikey as intended

horde_sdk/ai_horde_worker/model_meta.py, tests/ai_horde_worker/test_model_meta_api_calls.py
The dynamic I introduced with `AI_HORDE_MODEL_META_LARGE_MODELS` was confusing. Unfortunately, this is undoubtably going to create problems when workers start offering flux when they didn't intend to, but that's the cost of progress.
=> fix: resolve 'all' models when asked

horde_sdk/ai_horde_worker/model_meta.py, tests/ai_horde_worker/test_model_meta_api_calls.py
The dynamic I introduced with `AI_HORDE_MODEL_META_LARGE_MODELS` was confusing. Unfortunately, this is undoubtably going to create problems when workers start offering flux when they didn't intend to, but that's the cost of progress.
=> fix: resolve 'all' models when asked (#321)
